# Generated by Django 5.0.7 on 2025-07-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vet_name', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('video_link', models.URLField(blank=True)),
            ],
        ),
    ]
