# Generated by Django 5.0.7 on 2026-02-01 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=50)),
                ('exchange', models.CharField(default='NFO', max_length=10)),
                ('token', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('ema_period', models.IntegerField(default=20)),
                ('rsi_period', models.IntegerField(default=14)),
                ('st_period', models.IntegerField(default=7)),
                ('st_multiplier', models.DecimalField(decimal_places=2, default=3.0, max_digits=4)),
            ],
            options={
                'verbose_name_plural': 'Strategies',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noren_order_no', models.CharField(max_length=100, unique=True)),
                ('side', models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], max_length=10)),
                ('qty', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.strategy')),
            ],
        ),
    ]
