# Generated by Django 5.0.7 on 2026-02-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='sma_period',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='ema_period',
            field=models.IntegerField(default=50),
        ),
    ]
