# Generated by Django 5.0.7 on 2026-02-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_strategy_sma_period_alter_strategy_ema_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='st_multiplier',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='st_period',
        ),
        migrations.AddField(
            model_name='strategy',
            name='rsi_threshold',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='strategy',
            name='sl_pct',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='strategy',
            name='square_off',
            field=models.TimeField(default='15:15'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='start_time',
            field=models.TimeField(default='09:15'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='target_pct',
            field=models.FloatField(default=2.0),
        ),
    ]
