# Generated by Django 5.0.7 on 2026-02-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_remove_strategy_st_multiplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='ema_period',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='rsi_period',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='rsi_threshold',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='sma_period',
        ),
        migrations.AddField(
            model_name='strategy',
            name='logic_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
