<!DOCTYPE html>
<html lang="en" data-bs-theme="light">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FlashPaste Pro | Secure Sharing</title>
    
    <!-- PWA Meta Tags -->
    <link rel="manifest" href="manifest.json">
    <meta name="theme-color" content="#0d6efd">
    <link rel="apple-touch-icon" href="https://cdn-icons-png.flaticon.com/512/1621/1621635.png">

    <!-- CSS Dependencies -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/themes/prism-tomorrow.min.css" rel="stylesheet">
    <link rel="stylesheet" href="style.css">
    
    <!-- JS Libraries -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/prism.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/4.3.0/marked.min.js"></script>
</head>
<body>

<nav class="navbar navbar-expand navbar-dark bg-primary sticky-top shadow-sm">
    <div class="container">
        <span class="navbar-brand fw-bold">⚡ FLASH<span class="opacity-75">PASTE</span> PRO</span>
        <div class="ms-auto d-flex align-items-center">
            <button class="btn btn-sm btn-outline-light me-3" id="themeToggle">🌓 Mode</button>
            <span class="badge bg-white text-primary">PWA Active</span>
        </div>
    </div>
</nav>

<div class="container py-4">
    <div class="row g-4">
        <!-- SENDER SECTION -->
        <div class="col-lg-7">
            <div class="card border-0 shadow-sm p-4">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <h5 class="mb-0 fw-bold">📤 Share Content</h5>
                    <button class="btn btn-sm btn-primary" onclick="addSnippetInput()">+ Add Snippet</button>
                </div>

                <div id="drop-zone" class="p-4 border-dashed rounded text-center mb-3 text-muted small bg-light">
                    Drag & Drop .txt / .json files or click to add
                    <input type="file" id="fileInput" class="d-none" accept=".txt,.json">
                </div>
                
                <div id="snippet-container" class="mb-3"></div>

                <div class="row g-2">
                    <div class="col-md-6">
                        <div class="form-check form-switch p-2 border rounded">
                            <input class="form-check-input ms-0 me-2" type="checkbox" id="e2eeToggle" checked>
                            <label class="form-check-label small fw-bold" for="e2eeToggle">🔒 Local E2EE Encryption</label>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <button id="generateBtn" class="btn btn-primary w-100 fw-bold py-2 shadow-sm">GENERATE CODE</button>
                    </div>
                </div>

                <div id="codeResult" class="mt-4 p-4 bg-primary text-white rounded text-center d-none animate-fade-in shadow">
                    <p class="small mb-1 text-uppercase ls-2">Access Code</p>
                    <h1 class="display-1 fw-bold mb-0" id="finalCode">----</h1>
                    <div class="mt-2 x-small opacity-75">Encrypted locally. Server cannot read this data.</div>
                </div>
            </div>
        </div>

        <!-- RECEIVER SECTION -->
        <div class="col-lg-5">
            <div class="card border-0 shadow-sm p-4">
                <h5 class="fw-bold">📥 Retrieve Snippets</h5>
                <div class="input-group my-3">
                    <input type="text" id="accessCode" class="form-control form-control-lg text-center ls-5 fw-bold" placeholder="0000" maxlength="4">
                    <button class="btn btn-dark px-4 fw-bold" id="fetchBtn">FETCH</button>
                </div>

                <div id="displayArea" class="d-none">
                    <div id="fetched-snippets"></div>
                </div>
                
                <div id="welcomeMessage" class="text-center py-5 text-muted border-top">
                    <p class="small">Enter the 4-digit code generated by the sender.</p>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="script.js"></script>
<script>
    // PWA Service Worker Registration
    if ('serviceWorker' in navigator) {
        window.addEventListener('load', () => {
            navigator.serviceWorker.register('sw.js')
                .then(reg => console.log('Service Worker Registered'))
                .catch(err => console.log('Service Worker Failed', err));
        });
    }
</script>
</body>
</html>