# Generated by Django 5.0.7 on 2025-08-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_supplier_type_of_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingrental',
            name='contract_validity',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='contract_validity',
            field=models.DateField(blank=True, null=True),
        ),
    ]
