# Generated by Django 5.0.7 on 2025-09-05 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_alter_supplier_address_primary_alter_supplier_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='type_of_seller',
        ),
    ]
