# Generated by Django 5.0.7 on 2025-09-07 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_remove_supplier_type_of_seller'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingrepair',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='pendingrepair',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='pendingrepair',
            name='repair_date',
        ),
        migrations.AddField(
            model_name='pendingrepair',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingrepair',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pendingrepair',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pendingrepair',
            name='original_repair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentals.repair'),
        ),
        migrations.AlterField(
            model_name='pendingrepair',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.productasset'),
        ),
        migrations.AlterField(
            model_name='pendingrepair',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
