# Generated by Django 5.0.7 on 2025-09-07 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_productasset_revenue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
