# Generated by Django 5.0.7 on 2025-09-12 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0010_alter_pendingproduct_serial_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingproduct',
            name='hsn_code',
        ),
        migrations.RemoveField(
            model_name='productasset',
            name='hsn_code',
        ),
    ]
