# Generated by Django 5.0.7 on 2025-07-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_petschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petschedule',
            name='notified',
        ),
        migrations.AddField(
            model_name='petschedule',
            name='notified_today',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='petschedule',
            name='scheduled_time',
            field=models.TimeField(),
        ),
    ]
