# Generated by Django 5.0.7 on 2025-06-21 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number_primary', models.CharField(max_length=15)),
                ('phone_number_secondary', models.CharField(blank=True, max_length=15, null=True)),
                ('address_primary', models.TextField()),
                ('address_secondary', models.TextField(blank=True, null=True)),
                ('is_permanent', models.BooleanField(default=False)),
                ('is_bni_member', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI')], max_length=20)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partial'), ('unpaid', 'Unpaid')], default='unpaid', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(blank=True, max_length=50, null=True)),
                ('type_of_asset', models.CharField(choices=[('Laptop', 'Laptop'), ('Monitor', 'Monitor'), ('Printer', 'Printer'), ('Adaptor', 'Adaptor')], max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('model_no', models.CharField(max_length=100)),
                ('serial_no', models.CharField(max_length=100, unique=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateField()),
                ('under_warranty', models.BooleanField(default=False)),
                ('warranty_duration_months', models.PositiveIntegerField(blank=True, null=True)),
                ('purchased_from', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_config', models.DateField()),
                ('ram', models.CharField(blank=True, max_length=50, null=True)),
                ('hdd', models.CharField(blank=True, max_length=50, null=True)),
                ('ssd', models.CharField(blank=True, max_length=50, null=True)),
                ('graphics', models.CharField(blank=True, max_length=100, null=True)),
                ('display_size', models.CharField(blank=True, max_length=50, null=True)),
                ('power_supply', models.CharField(blank=True, max_length=100, null=True)),
                ('detailed_config', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=100, unique=True)),
                ('asset_tag', models.CharField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_start_date', models.DateField()),
                ('duration_days', models.PositiveIntegerField(blank=True)),
                ('rental_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('overdue', 'Overdue'), ('completed', 'Completed')], default='ongoing', max_length=20)),
            ],
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('name', 'phone_number_primary'), name='unique_customer_by_name_and_phone'),
        ),
        migrations.AddField(
            model_name='productconfiguration',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='rentals.productasset'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='rentals.productasset'),
        ),
        migrations.AddField(
            model_name='rental',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.customer'),
        ),
        migrations.AddField(
            model_name='rental',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.productunit'),
        ),
        migrations.AddField(
            model_name='payment',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.rental'),
        ),
    ]
