# Generated by Django 5.0.7 on 2025-06-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productasset',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
