# Generated by Django 5.0.7 on 2025-07-19 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingproduct',
            name='asset_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pendingproduct',
            name='asset_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingproduct',
            name='damage_narration',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingproduct',
            name='date_marked_dead',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingproduct',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='pendingproduct',
            name='sale_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingproduct',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pendingproduct',
            name='sold_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pendingproduct',
            name='condition_status',
            field=models.CharField(choices=[('working', 'Working'), ('damaged', 'Damaged'), ('missing', 'Missing'), ('sold', 'Sold')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pendingproduct',
            name='purchased_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentals.supplier'),
        ),
        migrations.AlterField(
            model_name='pendingproduct',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pendingproduct',
            name='type_of_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.assettype'),
        ),
    ]
