# Generated by Django 5.0.7 on 2025-06-21 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_productasset_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='productasset',
            name='quantity',
        ),
        migrations.AddField(
            model_name='rental',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentals.productasset'),
        ),
        migrations.DeleteModel(
            name='ProductUnit',
        ),
    ]
