# Generated by Django 5.0.7 on 2025-06-20 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_rename_address_customer_address_primary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_asset', models.CharField(choices=[('Laptop', 'Laptop'), ('Monitor', 'Monitor'), ('Printer', 'Printer'), ('Adaptor', 'Adaptor')], max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('model_no', models.CharField(max_length=100)),
                ('serial_no', models.CharField(max_length=100, unique=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateField()),
                ('under_warranty', models.BooleanField(default=False)),
                ('warranty_duration_months', models.PositiveIntegerField(blank=True, null=True)),
                ('purchased_from', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='productunit',
            name='model',
        ),
        migrations.AlterField(
            model_name='rental',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.productasset'),
        ),
        migrations.CreateModel(
            name='ProductConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_config', models.DateField()),
                ('ram', models.CharField(blank=True, max_length=50, null=True)),
                ('hdd', models.CharField(blank=True, max_length=50, null=True)),
                ('ssd', models.CharField(blank=True, max_length=50, null=True)),
                ('graphics', models.CharField(blank=True, max_length=100, null=True)),
                ('display_size', models.CharField(blank=True, max_length=50, null=True)),
                ('power_supply', models.CharField(blank=True, max_length=100, null=True)),
                ('detailed_config', models.TextField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='rentals.productasset')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductModel',
        ),
        migrations.DeleteModel(
            name='ProductUnit',
        ),
    ]
