# Generated by Django 5.0.7 on 2025-07-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_pendingproduct_asset_id_pendingproduct_asset_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingproduct',
            name='asset_suffix',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
