# Generated by Django 5.0.7 on 2025-08-02 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_pendingcustomer_original_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='type_of_seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='rentals.assettype'),
        ),
    ]
