# Generated by Django 5.0.7 on 2025-06-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_productasset_remove_productunit_model_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCollection',
        ),
        migrations.AddField(
            model_name='productasset',
            name='asset_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
