# Generated by Django 5.0.7 on 2025-06-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_remove_rental_unit_remove_productasset_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='contract_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rental',
            name='made_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rental',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
