# Generated by Django 5.0.7 on 2025-07-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_cpuoption_displaysizeoption_graphicsoption_hddoption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='reference_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pendingcustomer',
            name='reference_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
