# Generated by Django 5.0.7 on 2025-09-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_pendingrental_contract_validity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='address_primary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='gstin',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='GSTIN Number'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone_primary',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
