# Generated by Django 5.0.7 on 2025-06-21 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_rental_contract_number_rental_made_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='rental',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rentals.rental'),
        ),
    ]
