# Generated by Django 5.0.7 on 2025-06-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_delete_productcollection_productasset_asset_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productasset',
            name='asset_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
