# Generated by Django 5.0.7 on 2025-06-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_remove_rental_made_by_customer_edited_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='productasset',
            name='type_of_asset',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Monitor', 'Monitor'), ('Printer', 'Printer'), ('Adaptor', 'Adaptor'), ('Graphics', 'Graphics Card'), ('Desktop', 'Desktop'), ('Server', 'Server')], max_length=50),
        ),
    ]
