# Generated by Django 5.0.7 on 2025-06-26 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_productconfiguration_repair_cost_repair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='rentals.productasset'),
        ),
    ]
