# Generated by Django 5.0.7 on 2025-09-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_delete_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingproduct',
            name='serial_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productasset',
            name='serial_no',
            field=models.CharField(max_length=100),
        ),
    ]
