# Generated by Django 5.0.7 on 2025-06-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_alter_rental_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='productasset',
            name='condition_status',
            field=models.CharField(choices=[('working', 'Working'), ('damaged', 'Damaged'), ('missing', 'Missing')], default='working', max_length=20),
        ),
    ]
