# Generated by Django 5.0.7 on 2025-06-27 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0010_productasset_condition_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productasset',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productasset',
            name='sale_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productasset',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productasset',
            name='sold_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentals.customer'),
        ),
    ]
