# Generated by Django 5.0.7 on 2025-07-01 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0011_productasset_is_sold_productasset_sale_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_asset', models.CharField(choices=[('Laptop', 'Laptop'), ('Monitor', 'Monitor'), ('Printer', 'Printer'), ('Adaptor', 'Adaptor'), ('Graphics', 'Graphics Card'), ('Desktop', 'Desktop'), ('Server', 'Server')], max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('model_no', models.CharField(max_length=100)),
                ('serial_no', models.CharField(max_length=100, unique=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateField()),
                ('under_warranty', models.BooleanField(default=False)),
                ('warranty_duration_months', models.PositiveIntegerField(blank=True, null=True)),
                ('purchased_from', models.CharField(max_length=255)),
                ('condition_status', models.CharField(default='working', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
