# Generated by Django 5.0.7 on 2025-09-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0011_remove_pendingproduct_hsn_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingproductconfiguration',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productconfiguration',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
