# Generated by Django 5.0.7 on 2025-09-14 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0012_pendingproductconfiguration_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productasset',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productconfiguration',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='repair',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
