# Generated by Django 5.0.7 on 2025-07-02 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0013_pendingcustomer_pendingrental'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingrental',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='pendingrental',
            name='submitted_by',
        ),
        migrations.AddField(
            model_name='pendingrental',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pendingrental',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pendingrental',
            name='rental_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingrental',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('overdue', 'Overdue'), ('completed', 'Completed')], default='ongoing', max_length=20),
        ),
        migrations.AlterField(
            model_name='pendingrental',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentals.productasset'),
        ),
        migrations.AlterField(
            model_name='pendingrental',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
