# Generated by Django 5.0.7 on 2025-09-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0013_customer_edited_at_productasset_edited_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productasset',
            name='serial_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
