# Generated by Django 5.0.7 on 2025-09-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0014_alter_productasset_serial_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingrepair',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productasset',
            name='warranty_duration_months',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
