# Generated by Django 5.0.7 on 2025-09-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0017_pendingrepair_repair_warranty_months_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingproduct',
            name='serial_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
