# Generated by Django 5.0.7 on 2026-02-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_notice_studymaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='material_type',
            field=models.CharField(choices=[('FILE', 'Document/PDF'), ('IMAGE', 'Photo/Image'), ('TEXT', 'Written Notes')], default='FILE', max_length=10),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='study_materials/'),
        ),
    ]
